sudo: false
language: node_js
node_js:
- '10.13.0'
cache: yarn
branches:
  only:
  - master
notifications:
  email: false
  slack:
    on_success: always
before_script:
- yarn clean
script:
- yarn export
- touch out/.nojekyll
- touch out/CNAME
- echo "certs.turingchain.tech" > out/CNAME
env:
- DEPLOY_ENV=production PROJ_NAME=certs.turingchain.tech
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ./out
  on:
    branch: master